"""Update FinancialProfile

Revision ID: 07652cfc6615
Revises: 
Create Date: 2026-10-09 23:17:10.480225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07652cfc6615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wizard_data_json', sa.Text(), nullable=True))
        batch_op.drop_column('variable_expenses_json')
        batch_op.drop_column('total_monthly_debt')
        batch_op.drop_column('fixed_expenses_json')
        batch_op.drop_column('gross_annual_income')
        batch_op.drop_column('existing_emergency_fund')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('existing_emergency_fund', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gross_annual_income', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('fixed_expenses_json', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('total_monthly_debt', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('variable_expenses_json', sa.TEXT(), nullable=True))
        batch_op.drop_column('wizard_data_json')

    # ### end Alembic commands ###
